"""Estilos recomendados.

Cada preset es un `StyleSpec` completo: define ritmo, transiciones, color,
audio y estructura. El usuario puede elegir uno y quedarse ahí, o usarlo como
base y afinarlo con un prompt.
"""

from __future__ import annotations

from copy import deepcopy

from ..models import StyleSpec, TextPlan, TextStyle


def _style(**kwargs) -> StyleSpec:
    return StyleSpec(**kwargs)


PRESETS: dict[str, StyleSpec] = {
    "dynamic": _style(
        id="dynamic",
        name="Dinámico",
        emoji="⚡",
        description="Cortes rápidos al ritmo de la música, color vivo. Ideal para Reels y TikTok.",
        aspect="9:16",
        min_clip=0.6,
        max_clip=2.2,
        target_clip=1.2,
        beat_sync=True,
        beat_division=2,
        transitions=["cut", "cut", "cut", "zoomin", "slideleft"],
        transition_chance=0.25,
        transition_duration=0.22,
        effects=["zoom_punch", "none", "kenburns_in"],
        effect_chance=0.55,
        image_effects=["zoom_punch", "kenburns_in"],
        grade="vivid",
        music_volume=0.9,
        original_audio_volume=0.0,
        order="energy_ramp",
        energy_ramp=True,
    ),
    "beatsync": _style(
        id="beatsync",
        name="Beat Sync",
        emoji="🥁",
        description="Un corte por pulso, sin transiciones. Máxima sincronía con la música.",
        aspect="9:16",
        min_clip=0.35,
        max_clip=1.6,
        target_clip=0.7,
        beat_sync=True,
        beat_division=1,
        transitions=["cut"],
        transition_chance=0.0,
        effects=["zoom_punch", "none"],
        effect_chance=0.7,
        image_effects=["zoom_punch"],
        grade="vivid",
        music_volume=1.0,
        original_audio_volume=0.0,
        order="by_score",
    ),
    "cinematic": _style(
        id="cinematic",
        name="Cinematográfico",
        emoji="🎞️",
        description="Planos largos, fundidos suaves y color teal & orange. Respira.",
        aspect="16:9",
        min_clip=2.5,
        max_clip=6.5,
        target_clip=4.0,
        beat_sync=False,
        beat_division=8,
        transitions=["dissolve", "fade", "cut"],
        transition_chance=0.6,
        transition_duration=0.8,
        effects=["slow_drift", "none"],
        effect_chance=0.5,
        image_effects=["kenburns_in", "kenburns_left"],
        grade="teal_orange",
        music_volume=0.6,
        original_audio_volume=0.25,
        order="chronological",
        text=TextPlan(
            intro_title=True,
            style=TextStyle(size=72, y=0.5, animation="fade", uppercase=True),
        ),
    ),
    "vlog": _style(
        id="vlog",
        name="Vlog",
        emoji="📹",
        description="Ritmo natural, conserva tu voz y baja la música cuando hablas.",
        aspect="16:9",
        min_clip=1.8,
        max_clip=5.0,
        target_clip=3.0,
        beat_sync=False,
        transitions=["cut", "cut", "fade"],
        transition_chance=0.2,
        transition_duration=0.35,
        effects=["none"],
        effect_chance=0.1,
        image_effects=["kenburns_in"],
        grade="warm",
        music_volume=0.28,
        original_audio_volume=1.0,
        duck_music=True,
        order="chronological",
    ),
    "travel": _style(
        id="travel",
        name="Viaje",
        emoji="🌍",
        description="Montaje de viaje: paisajes amplios, ritmo medio-alto y color cálido.",
        aspect="9:16",
        min_clip=1.0,
        max_clip=3.0,
        target_clip=1.8,
        beat_sync=True,
        beat_division=2,
        transitions=["cut", "slideleft", "wipeleft", "dissolve"],
        transition_chance=0.4,
        transition_duration=0.35,
        effects=["kenburns_in", "slow_drift", "none"],
        effect_chance=0.6,
        image_effects=["kenburns_in", "kenburns_right"],
        grade="warm",
        music_volume=0.85,
        original_audio_volume=0.12,
        order="chronological",
        text=TextPlan(intro_title=True, style=TextStyle(size=64, y=0.12)),
    ),
    "slideshow": _style(
        id="slideshow",
        name="Recuerdos",
        emoji="🖼️",
        description="Pensado para fotos: paneo lento y encadenados largos.",
        aspect="16:9",
        min_clip=2.5,
        max_clip=5.0,
        target_clip=3.2,
        beat_sync=True,
        beat_division=8,
        transitions=["dissolve", "fade"],
        transition_chance=0.9,
        transition_duration=1.0,
        effects=["kenburns_in", "kenburns_out", "kenburns_left", "kenburns_right"],
        effect_chance=1.0,
        image_effects=["kenburns_in", "kenburns_out", "kenburns_left", "kenburns_right"],
        grade="faded",
        fit="blur_pad",
        music_volume=0.75,
        original_audio_volume=0.0,
        order="chronological",
    ),
    "trailer": _style(
        id="trailer",
        name="Tráiler",
        emoji="🍿",
        description="Arranque lento que acelera hasta el clímax, con fundidos a negro.",
        aspect="16:9",
        min_clip=0.5,
        max_clip=5.0,
        target_clip=2.0,
        beat_sync=True,
        beat_division=4,
        energy_ramp=True,
        transitions=["fadeblack", "cut", "cut", "flash"],
        transition_chance=0.35,
        transition_duration=0.4,
        effects=["zoom_punch", "slow_drift", "none"],
        effect_chance=0.5,
        image_effects=["zoom_punch", "kenburns_in"],
        grade="cinematic",
        music_volume=0.95,
        original_audio_volume=0.15,
        order="energy_ramp",
        text=TextPlan(
            intro_title=True,
            outro_text="",
            style=TextStyle(size=88, y=0.5, uppercase=True, animation="pop", stroke=2),
        ),
    ),
    "aesthetic": _style(
        id="aesthetic",
        name="Estético",
        emoji="🌸",
        description="Suave y lavado, movimiento lento y transiciones fluidas.",
        aspect="9:16",
        min_clip=1.6,
        max_clip=4.0,
        target_clip=2.6,
        beat_sync=True,
        beat_division=4,
        transitions=["dissolve", "smoothleft", "fadewhite"],
        transition_chance=0.7,
        transition_duration=0.6,
        effects=["slow_drift", "kenburns_in"],
        effect_chance=0.8,
        image_effects=["kenburns_in", "slow_drift"],
        grade="faded",
        music_volume=0.8,
        original_audio_volume=0.0,
        order="by_score",
    ),
    "sport": _style(
        id="sport",
        name="Acción",
        emoji="🏄",
        description="Deporte y acción: cortes secos, zooms y contraste alto.",
        aspect="9:16",
        min_clip=0.5,
        max_clip=1.8,
        target_clip=1.0,
        beat_sync=True,
        beat_division=1,
        transitions=["cut", "cut", "zoomin", "radial"],
        transition_chance=0.2,
        transition_duration=0.18,
        effects=["zoom_punch", "shake", "none"],
        effect_chance=0.75,
        image_effects=["zoom_punch"],
        grade="vivid",
        music_volume=0.95,
        original_audio_volume=0.2,
        order="energy_ramp",
        energy_ramp=True,
    ),
    "wedding": _style(
        id="wedding",
        name="Boda",
        emoji="💍",
        description="Romántico: encadenados largos, tonos cálidos y ritmo pausado.",
        aspect="16:9",
        min_clip=2.5,
        max_clip=6.0,
        target_clip=3.8,
        beat_sync=True,
        beat_division=8,
        transitions=["dissolve", "fadewhite", "fade"],
        transition_chance=0.85,
        transition_duration=0.9,
        effects=["slow_drift", "kenburns_in"],
        effect_chance=0.7,
        image_effects=["kenburns_in", "kenburns_out"],
        grade="warm",
        music_volume=0.7,
        original_audio_volume=0.2,
        order="chronological",
        text=TextPlan(intro_title=True, style=TextStyle(size=68, y=0.5, animation="fade")),
    ),
    "talking": _style(
        id="talking",
        name="A cámara",
        emoji="🎙️",
        description="Entrevistas y piezas habladas: mantiene el audio y corta lo justo.",
        aspect="9:16",
        min_clip=3.0,
        max_clip=12.0,
        target_clip=6.0,
        beat_sync=False,
        transitions=["cut"],
        transition_chance=0.05,
        transition_duration=0.25,
        effects=["none"],
        effect_chance=0.0,
        image_effects=["kenburns_in"],
        grade="none",
        music_volume=0.12,
        original_audio_volume=1.0,
        duck_music=True,
        order="chronological",
        use_highlights=False,
    ),
    "promo": _style(
        id="promo",
        name="Promo",
        emoji="🛍️",
        description="Producto o marca: limpio, rítmico y con espacio para texto.",
        aspect="4:5",
        min_clip=0.9,
        max_clip=2.6,
        target_clip=1.5,
        beat_sync=True,
        beat_division=2,
        transitions=["cut", "slideup", "wipeleft"],
        transition_chance=0.35,
        transition_duration=0.28,
        effects=["zoom_punch", "kenburns_in", "none"],
        effect_chance=0.5,
        image_effects=["kenburns_in", "zoom_punch"],
        grade="vivid",
        music_volume=0.85,
        original_audio_volume=0.1,
        order="by_score",
        text=TextPlan(intro_title=True, style=TextStyle(size=70, y=0.15, box=True)),
    ),
}


def get_preset(preset_id: str) -> StyleSpec:
    """Devuelve una copia del preset (nunca la instancia compartida)."""
    base = PRESETS.get(preset_id) or PRESETS["dynamic"]
    return deepcopy(base)


def list_presets() -> list[dict]:
    return [
        {
            "id": s.id,
            "name": s.name,
            "emoji": s.emoji,
            "description": s.description,
            "aspect": s.aspect,
            "target_clip": s.target_clip,
            "grade": s.grade,
            "beat_sync": s.beat_sync,
        }
        for s in PRESETS.values()
    ]
